import Sidebar from "@/components/layout/Sidebar";
import clsx from "clsx";
import Head from "next/head";
import React, { FC } from "react";
import { ReactNode } from "react";
import { BreadcrumbItem } from "./Breadcrumbs";
import { Navbar } from "./Navbar";

function DefaultBody(props: { children: ReactNode }) {
    return (
        <div className="overflow-y-auto flex flex-col">{props.children}</div>
    );
}

export function AppLayout({
    items,
    children,
    breadcrumb,
    layout: Body = DefaultBody,
}: {
    breadcrumb?: BreadcrumbItem[];
    items?: ReactNode;
    children?: ReactNode;
    layout?: FC<{ children: ReactNode }>;
}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main
                className={clsx(
                    "grid grid-cols-1 md:grid-cols-[20rem_auto] h-screen text-accent-900 bg-light-100",
                    "dark:text-accent-50 dark:bg-dark-900"
                )}
            >
                <Sidebar />
                <Body>
                    <Navbar breadcrumb={breadcrumb}>{items}</Navbar>
                    <div className="max-w-screen-2xl w-full mx-auto flex flex-col flex-1 pt-2 p-4">
                        {children}
                    </div>
                </Body>
            </main>
        </>
    );
}
