import Head from "next/head";
import { ReactNode } from "react";

export function BaseLayout({ children }: { children: ReactNode }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex flex-col min-h-screen text-accent-900 dark:text-accent-50 bg-light-100 dark:bg-dark-900 p-4">
                {children}
            </main>
        </>
    );
}
