import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import { GetBookQuery, GetBookQueryVariables } from "@/gql/generated/graphql";

const GET_BOOK = gql`
    query getBook {
        book
    }
`;

export default function Home() {
    const { data, loading } = useQuery<GetBookQuery, GetBookQueryVariables>(
        GET_BOOK
    );

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <p>
                        {data?.book} {loading}
                    </p>
                </div>
            </main>
        </>
    );
}
