import { GetBookQuery, GetBookQueryVariables } from "@/gql/generated/graphql";
import styles from "@/styles/Home.module.css";
import { gql, useQuery, useSubscription } from "@apollo/client";
import Head from "next/head";

const GET_BOOK = gql`
    query getBook {
        book
    }
`;

const CHAT_SUBSCRIPTION = gql`
    subscription onChat {
        counter
    }
`;

export default function Home() {
    const { data, loading } = useQuery<GetBookQuery, GetBookQueryVariables>(
        GET_BOOK
    );

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <Counter />
                    <p>
                        {data?.book} {loading}
                    </p>
                </div>
            </main>
        </>
    );
}

function Counter() {
    const { data, loading } = useSubscription(CHAT_SUBSCRIPTION);

    return <p>{data?.counter}</p>;
}
